### ISSUE TITLE
Add support for jakarta implementation

### ISSUE THREAD

**Issue by gdinant** [wallee-payment/java-sdk#7]
Hello there,

When running your library under springboot 3 which enforces the usage of `jakarta` instead of `javax` I run into the following error:

```java
 javax/ws/rs/core/UriBuilder] with root cause
java.lang.ClassNotFoundException: javax.ws.rs.core.UriBuilder
	at com.wallee.sdk.service.CustomerService.searchForHttpResponse(CustomerService.java:673)
	at com.wallee.sdk.service.CustomerService.search(CustomerService.java:631)
	at com.ecowaste.service.service.payment.PostFinanceService.lambda$findPostFinanceCustomers$4bebc60d$1(PostFinanceService.java:201)
	at io.vavr.control.Try.of(Try.java:75)
	at com.ecowaste.service.service.payment.PostFinanceService.findPostFinanceCustomers(PostFinanceService.java:200)
	at com.ecowaste.service.service.payment.PostFinanceService.lambda$createPostFinanceTransaction$8(PostFinanceService.java:187)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at com.ecowaste.service.service.payment.PostFinanceService.createPostFinanceTransaction(PostFinanceService.java:187)
	at com.ecowaste.service.service.payment.PostFinanceService.lambda$createTransaction$d6cd55fc$1(PostFinanceService.java:139)
	at io.vavr.control.Try.of(Try.java:75)
	at com.ecowaste.service.service.payment.PostFinanceService.createTransaction(PostFinanceService.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
``` 

Your library already pulls in jakarta dependencies but still has a single reference on javax.ws.rs for the UriBuilder.

Would you be able to make a fix?

Thanks :)

**Comment by theodorspringwallee** [comment]
Dear [gdinant](https://github.com/gdinant)

I forwarded your request to our developers.

Best regards
